spring.cloud.config.enabled=false
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/task_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Feign Circuitbreaker - required for FallbackFactory to work
spring.cloud.openfeign.circuitbreaker.enabled=true

# Retry Configuration
resilience4j.retry.instances.Task-Service.max-attempts=5
resilience4j.retry.instances.Task-Service.wait-duration=2s
resilience4j.retry.instances.Task-Service.retry-exceptions=java.net.ConnectException,java.io.IOException
resilience4j.retry.instances.Task-Service.ignore-exceptions=com.cts.exception.ResourceNotFoundException,com.cts.exception.ServiceUnavailableException
